---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reviewer
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.urlPrefix }}.cloudapp.azure.com
    secretName: reviewer-key
  rules:
  - host: {{ .Values.urlPrefix }}.cloudapp.azure.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: reviewer-api
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reviewer-ui
            port:
              number: 80
